# This is a basic workflow to help you get started with Actions

name: Record event on devprogramresources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - Parsers/**
      - Interaction/**
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   issues:
#     types: [opened, closed]
#     branches: main
#   pull_request_target:
#     types: [opened, closed]
#     branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    if: github.repository == 'ServiceNowDevProgram/SlackerBot'
    runs-on: ubuntu-latest
    steps:
    - name: Log payload
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Contact DPR
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ format('https://{0}.service-now.com/api/x_snc_slackerbot/slackerbotgithub', secrets.SN_INSTANCE_NAME) }}
#         url: 'https://devprogramresources.service-now.com/api/x_snc_slackerbot/slackerbotgithub'
#         url: 'https://earl.service-now.com/api/x_snc_slackerbot/slackerbotgithub'
        method: 'POST'
        contentType: application/json
        data: ${{ toJson(github) }}
        username: ${{ secrets.ADMIN_USERNAME }}
        password: ${{ secrets.ADMIN_PASSWORD }}
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
